### ISSUE TITLE
The action.yml has extra space characters at ends of a couple lines

### ISSUE THREAD

**Issue by Fran-Rg** [cicirello/python-github-action-template#13]
**Describe the bug**
The action.yml contains few yaml errors, extra spaces, extra tabs

**To Reproduce**
1. Install yamllint https://github.com/adrienverge/yamllint
2. `yamllint --strict .`

**Expected behavior**
No error

**Additional context**
It would be good to run a yamllint check on PR:
```
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
